server:
  port: 8000
spring:
  application:
    name: JpaDemo
  datasource:
    password: 123
    username: root
    url: jdbc:postgresql://192.168.27.128:5432/postgres?currentSchema=demo
    driver-class-name: org.postgresql.Driver
    hikari:
      connection-timeout: 200000
      maximum-pool-size: 20
  jpa:
    show-sql: true
#    database-platform: org.hibernate.dialect.PostgreSQLDialect  # ?????
    hibernate:
      ddl-auto: validate
    open-in-view: true






